[KLC-984] Prevent native Multi-Contract if SmartContract is been called && Refactor Simulator Processor. (#808)
* chore: avoid totalConsumedGas be overwrited

* update unused errors

* refactor simulator && allow only 1 contract with SC execution

* refactor tx processor

* [KLC-1044] VMOutput Compute Total Consumed Gas by logs

* Refactor economics process TX to prevent more than one SC per tx

* Improve unit tests

- vmOutput Tests
- CostEstimator Tests
- Economics Data tests
- Simulate TXProcess

* Check fail git workflow

* update result code before return error

---------

Co-authored-by: Fernando Sobreira <fbsobreira@gmail.com>

diff --git a/.github/workflows/pr-qa-sec.yaml b/.github/workflows/pr-qa-sec.yaml
--- a/.github/workflows/pr-qa-sec.yaml
+++ b/.github/workflows/pr-qa-sec.yaml
@@ -319,3 +319,15 @@ jobs:
           REPORT_URL: ${{ env.REPORT_URL }}
           REVIEW_URL: ${{ env.REVIEW_URL }}
           REVIEW_TEXT: ${{ env.REVIEW_TEXT }}
+
+
+  result-check:
+    needs: [sonarqube, test]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for failed jobs
+        run: |
+          if [[ "${{ needs.sonarqube.result }}" == "failure" || "${{ needs.test.outputs.test_exit_code }}" == "1" ]]; then
+            echo "One or more jobs failed. Exiting with status 1."
+            exit 1
+          fi
